name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: touch wrxue
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: touch weirenxue
      - run: echo ${{ secrets.SECRET_TEST }} > test.txt
      - run: cat test.txt
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls
