name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: touch wrxue
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: touch weirenxue
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls
